# Generated by Django 3.0.12 on 2021-04-11 13:24

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import roomsharing.rooms.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rs_organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Name")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="question-circle", max_length=25, verbose_name="Icon"
                    ),
                ),
            ],
            options={
                "verbose_name": "Amenity",
                "verbose_name_plural": "Amenities",
            },
        ),
        migrations.CreateModel(
            name="Aptitude",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, unique=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="question-circle", max_length=25, verbose_name="Icon"
                    ),
                ),
            ],
            options={
                "verbose_name": "Aptitude",
                "verbose_name_plural": "Aptitudes",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=4000,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "capacity_from",
                    models.IntegerField(default=10, verbose_name="Capacity from"),
                ),
                (
                    "capacity_to",
                    models.IntegerField(default=15, verbose_name="Capacity to"),
                ),
                (
                    "square_meters",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Square Meters"
                    ),
                ),
                (
                    "rules",
                    models.TextField(
                        blank=True, max_length=2000, null=True, verbose_name="Rules"
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="Published"),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from=["organization", "name"],
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rooms_of_organization",
                        related_query_name="room_of_organization",
                        to="rs_organizations.Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
                "unique_together": {("name", "organization")},
            },
        ),
        migrations.CreateModel(
            name="RoomImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=roomsharing.rooms.models.roomimage_path
                    ),
                ),
                ("alt_description", models.CharField(max_length=200)),
                (
                    "order",
                    models.IntegerField(
                        default=1,
                        help_text="The image with the lowest number is shown first.",
                        null=True,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roomimages_of_room",
                        related_query_name="roomimage_of_room",
                        to="rooms.Room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Image",
                "verbose_name_plural": "Room Images",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="RoomAptitude",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specification",
                    models.CharField(
                        blank=True,
                        max_length=400,
                        null=True,
                        verbose_name="Specification",
                    ),
                ),
                (
                    "aptitude",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roomaptitudes_of_aptitude",
                        related_query_name="roomaptitude_of_aptitude",
                        to="rooms.Aptitude",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roomaptitudes_of_room",
                        related_query_name="roomaptitude_of_room",
                        to="rooms.Room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Aptitude",
                "verbose_name_plural": "Room Aptitudes",
                "unique_together": {("room", "aptitude")},
            },
        ),
        migrations.CreateModel(
            name="RoomAmenity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specification",
                    models.CharField(
                        blank=True,
                        max_length=400,
                        null=True,
                        verbose_name="Specification",
                    ),
                ),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roomamenities_of_amenity",
                        related_query_name="roomamenity_of_aptitude",
                        to="rooms.Amenity",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roomamenities_of_room",
                        related_query_name="roomamenity_of_room",
                        to="rooms.Room",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room Amenity",
                "verbose_name_plural": "Room Amenities",
                "unique_together": {("room", "amenity")},
            },
        ),
    ]
