# Generated by Django 3.0.12 on 2021-02-28 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "description",
                    models.TextField(max_length=4000, verbose_name="Description"),
                ),
                (
                    "capacity_from",
                    models.IntegerField(default=10, verbose_name="Capacity from"),
                ),
                (
                    "capacity_to",
                    models.IntegerField(default=15, verbose_name="Capacity to"),
                ),
                (
                    "square_meters",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Square Meters"
                    ),
                ),
                (
                    "rules",
                    models.TextField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        verbose_name="Square Meters",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="Published"),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_of_room",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
