# Generated by Django 3.0.12 on 2021-03-21 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Name")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-question-circle", max_length=25, verbose_name="Icon"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Aptitude",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Name")),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        default="bi-question-circle", max_length=25, verbose_name="Icon"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomAptitude",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specification",
                    models.CharField(max_length=400, verbose_name="Specification"),
                ),
                (
                    "aptitude",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roomaptitudes_of_aptitude",
                        related_query_name="roomaptitude_of_aptitude",
                        to="rooms.Aptitude",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roomaptitudes_of_room",
                        related_query_name="roomaptitude_of_room",
                        to="rooms.Room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoomAmenity",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specification",
                    models.CharField(max_length=400, verbose_name="Specification"),
                ),
                (
                    "amenity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roomamenities_of_amenity",
                        related_query_name="roomamenity_of_aptitude",
                        to="rooms.Aptitude",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roomamenities_of_room",
                        related_query_name="roomamenity_of_room",
                        to="rooms.Room",
                    ),
                ),
            ],
        ),
    ]
