# Generated by Django 3.0.12 on 2021-03-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rs_organizations", "0001_initial"),
        ("rooms", "0002_amenity_aptitude_roomamenity_roomaptitude"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amenity",
            options={"verbose_name": "Amenity", "verbose_name_plural": "Amenities"},
        ),
        migrations.AlterModelOptions(
            name="aptitude",
            options={"verbose_name": "Aptitude", "verbose_name_plural": "Aptitudes"},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "Room", "verbose_name_plural": "Rooms"},
        ),
        migrations.AlterModelOptions(
            name="roomamenity",
            options={
                "verbose_name": "Room Amenity",
                "verbose_name_plural": "Room Amenities",
            },
        ),
        migrations.AlterModelOptions(
            name="roomaptitude",
            options={
                "verbose_name": "Room Aptitude",
                "verbose_name_plural": "Room Aptitudes",
            },
        ),
        migrations.RenameField(
            model_name="room",
            old_name="owner_organisation",
            new_name="owner_organization",
        ),
        migrations.AlterField(
            model_name="aptitude",
            name="name",
            field=models.CharField(max_length=30, unique=True, verbose_name="Name"),
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("name", "owner_organization")},
        ),
        migrations.AlterUniqueTogether(
            name="roomamenity",
            unique_together={("room", "amenity")},
        ),
        migrations.AlterUniqueTogether(
            name="roomaptitude",
            unique_together={("room", "aptitude")},
        ),
    ]
