# Generated by Django 3.0.12 on 2021-04-05 15:44

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("rs_organizations", "0001_initial"),
        ("rooms", "0005_roomimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="roomimage",
            options={
                "ordering": ["order"],
                "verbose_name": "Room Image",
                "verbose_name_plural": "Room Images",
            },
        ),
        migrations.RenameField(
            model_name="room",
            old_name="owner_organization",
            new_name="organization",
        ),
        migrations.AddField(
            model_name="room",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from=["organization", "name"]
            ),
        ),
        migrations.AlterField(
            model_name="amenity",
            name="description",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="amenity",
            name="icon",
            field=models.CharField(
                default="question-circle", max_length=25, verbose_name="Icon"
            ),
        ),
        migrations.AlterField(
            model_name="aptitude",
            name="description",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="aptitude",
            name="icon",
            field=models.CharField(
                default="question-circle", max_length=25, verbose_name="Icon"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(
                blank=True, max_length=4000, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="rules",
            field=models.TextField(
                blank=True, max_length=2000, null=True, verbose_name="Rules"
            ),
        ),
        migrations.AlterField(
            model_name="roomamenity",
            name="specification",
            field=models.CharField(
                blank=True, max_length=400, null=True, verbose_name="Specification"
            ),
        ),
        migrations.AlterField(
            model_name="roomaptitude",
            name="specification",
            field=models.CharField(
                blank=True, max_length=400, null=True, verbose_name="Specification"
            ),
        ),
        migrations.AlterField(
            model_name="roomimage",
            name="order",
            field=models.IntegerField(
                default=1,
                help_text="The image with the lowest number is shown first.",
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("name", "organization")},
        ),
    ]
