# Generated by Django 3.0.12 on 2021-04-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rs_organizations', '0002_auto_20210418_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationaladdress',
            name='street_number',
        ),
        migrations.RemoveField(
            model_name='organizationaladdress',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='organizationaladdress',
            name='building_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Building Number'),
        ),
        migrations.AddField(
            model_name='organizationaladdress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Postal Code'),
        ),
    ]
